"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, RefreshCw, Search, TerminalSquare } from "lucide-react";
import { Panel, Pill, Skeleton, rise } from "@/components/ui/kit";

type AgentEvent = { id: string; kind: string; title: string; detail: string | null; agent: string; level: string; meta?: unknown; createdAt: string };
type KindFilter = "all" | "run" | "status";
type CountRow = { label: string; count: number };
type ThroughputBucket = { start: number; count: number };

function parseDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; }
function formatTime(value: string) { const date = parseDate(value); return date ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit", second: "2-digit" }).format(date) : "Unknown time"; }
function compactTime(value: number) { return new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(value); }
function timeAgo(value: string | null) { if (!value) return "—"; const date = parseDate(value); if (!date) return "—"; const seconds = Math.round((date.getTime() - Date.now()) / 1000); const f = new Intl.RelativeTimeFormat(undefined, { numeric: "auto" }); if (Math.abs(seconds) < 60) return f.format(seconds, "second"); const minutes = Math.round(seconds / 60); if (Math.abs(minutes) < 60) return f.format(minutes, "minute"); const hours = Math.round(minutes / 60); return Math.abs(hours) < 48 ? f.format(hours, "hour") : f.format(Math.round(hours / 24), "day"); }
function label(value: string) { return value.replace(/[_-]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function tone(level: string): "neutral" | "up" | "down" | "warn" | "accent" { const value = level.toLowerCase(); if (["error", "down", "fail", "critical"].some((part) => value.includes(part))) return "down"; if (["warn", "attention"].some((part) => value.includes(part))) return "warn"; if (["up", "success", "online"].some((part) => value.includes(part))) return "up"; if (["active", "run"].some((part) => value.includes(part))) return "accent"; return "neutral"; }
function countBy(events: AgentEvent[], value: (event: AgentEvent) => string): CountRow[] { const counts = new Map<string, number>(); for (const event of events) { const key = value(event).trim(); if (key) counts.set(key, (counts.get(key) ?? 0) + 1); } return [...counts].map(([item, count]) => ({ label: item, count })).sort((a, b) => b.count - a.count || a.label.localeCompare(b.label)); }
function bucketEvents(events: AgentEvent[]): ThroughputBucket[] { const stamps = events.map((event) => parseDate(event.createdAt)?.getTime()).filter((value): value is number => value != null).sort((a, b) => a - b); if (!stamps.length) return []; if (stamps[0] === stamps[stamps.length - 1]) return [{ start: stamps[0], count: stamps.length }]; const bucketCount = Math.min(12, Math.max(4, Math.ceil(Math.sqrt(stamps.length)))); const span = stamps[stamps.length - 1] - stamps[0]; const width = span / bucketCount; const buckets = Array.from({ length: bucketCount }, (_, index) => ({ start: stamps[0] + index * width, count: 0 })); for (const stamp of stamps) buckets[Math.min(bucketCount - 1, Math.floor((stamp - stamps[0]) / width))].count += 1; return buckets; }

export default function ActivityPage() {
  const [events, setEvents] = useState<AgentEvent[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const [kind, setKind] = useState<KindFilter>("all"); const [level, setLevel] = useState("all"); const [query, setQuery] = useState("");
  const load = useCallback(async (quiet = false) => { if (quiet) setRefreshing(true); else setLoading(true); setError(null); try { const response = await fetch("/api/hermes/activity?take=100", { cache: "no-store" }); if (!response.ok) throw new Error(`Request failed (${response.status})`); const data = await response.json() as { events?: AgentEvent[] }; setEvents(data.events ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load activity."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { const frame = requestAnimationFrame(() => { void load(); }); return () => cancelAnimationFrame(frame); }, [load]);
  const identities = useMemo(() => [...new Set(events.map((event) => event.agent?.trim()).filter(Boolean))].sort(), [events]);
  const kinds = useMemo(() => [...new Set(events.map((event) => event.kind?.trim()).filter(Boolean))].sort(), [events]);
  const levels = useMemo(() => [...new Set(events.map((event) => event.level?.trim()).filter(Boolean))].sort(), [events]);
  const typeCounts = useMemo(() => countBy(events, (event) => event.kind), [events]);
  const topSources = useMemo(() => countBy(events, (event) => event.title).slice(0, 5), [events]);
  const throughput = useMemo(() => bucketEvents(events), [events]);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return events.filter((event) => { if (kind !== "all" && event.kind.toLowerCase() !== kind) return false; if (level !== "all" && event.level !== level) return false; return !needle || [event.agent, event.title, event.detail, event.kind, event.level].some((value) => value?.toLowerCase().includes(needle)); }); }, [events, kind, level, query]);
  const visible = filtered.slice(0, 15);
  const clearFilters = () => { setKind("all"); setLevel("all"); setQuery(""); };

  return <div className="relative z-10 w-full space-y-7 pb-16 pt-7">
    <header className="hq-rise flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between" style={rise(0)}><div><div className="eyebrow mb-1.5">Hermes operations</div><h1 className="text-[30px] font-semibold tracking-[-0.03em] text-[var(--text)] sm:text-[34px]">Activity</h1><p className="mt-1 max-w-xl text-[12.5px] text-[var(--text-3)]">Live and historical events across Hermes operations.</p></div><button onClick={() => void load(true)} disabled={refreshing} className="btn-ghost flex items-center gap-2 self-start px-3.5 py-2 text-[12px] sm:self-auto"><RefreshCw className={`h-3.5 w-3.5 ${refreshing ? "animate-spin" : ""}`} />Refresh</button></header>
    <section className="hq-rise" style={rise(60)}><Panel className="overflow-hidden"><div className="grid lg:grid-cols-[minmax(0,1.55fr)_minmax(260px,0.75fr)]"><div className="border-b border-[var(--line)] p-5 sm:p-6 lg:border-b-0 lg:border-r"><div className="flex items-start justify-between gap-4"><div><div className="eyebrow">Loaded event window</div><h2 className="mt-1.5 text-[20px] font-semibold tracking-[-0.02em] text-[var(--text)]">Event Throughput</h2><p className="mt-1 text-[11.5px] text-[var(--text-3)]">Timestamp distribution across the current API result.</p></div><Activity className="h-5 w-5 text-[var(--accent)]" /></div>{loading ? <Skeleton className="mt-6 h-40" /> : <ThroughputChart buckets={throughput} />}</div><div className="p-5 sm:p-6"><div className="eyebrow">Operational snapshot</div><div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-6"><Snapshot label="Events loaded" value={loading ? "…" : String(events.length)} note="Current API result" /><Snapshot label="Latest event" value={loading ? "…" : timeAgo(events[0]?.createdAt ?? null)} note="Within loaded result" /><Snapshot label="Attributed identities" value={loading ? "…" : String(identities.length)} note={identities.join(", ") || "None loaded"} /><Snapshot label="Event types" value={loading ? "…" : String(kinds.length)} note={kinds.map(label).join(", ") || "None loaded"} /></div></div></div></Panel></section>
    <section className="hq-rise" style={rise(110)}><Panel className="p-3 sm:p-4"><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap gap-1.5">{(["all", "run", "status"] as KindFilter[]).map((item) => <button key={item} onClick={() => setKind(item)} className={`rounded-lg px-3 py-1.5 text-[11.5px] font-medium transition-colors ${kind === item ? "bg-[var(--surface-3)] text-[var(--text)]" : "text-[var(--text-3)] hover:bg-[var(--surface-2)] hover:text-[var(--text-2)]"}`}>{label(item)}<span className="num ml-1.5 text-[var(--text-4)]">{item === "all" ? events.length : events.filter((event) => event.kind.toLowerCase() === item).length}</span></button>)}</div><div className="flex flex-col gap-2 sm:flex-row"><select aria-label="Filter by event level" value={level} onChange={(event) => setLevel(event.target.value)} className="rounded-lg border border-[var(--line)] bg-[var(--surface-2)] px-3 py-2 text-[12px] text-[var(--text-2)] outline-none"><option value="all">All levels</option>{levels.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><label className="relative min-w-0 sm:w-64"><Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[var(--text-4)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search event history" className="w-full rounded-lg border border-[var(--line)] bg-[var(--surface-2)] py-2 pl-9 pr-3 text-[12px] text-[var(--text)] outline-none placeholder:text-[var(--text-4)]" /></label></div></div></Panel></section>
    {error && <Panel className="flex flex-col items-start justify-between gap-3 p-4 sm:flex-row sm:items-center"><div className="flex items-center gap-2 text-[13px] text-[var(--down)]"><AlertTriangle className="h-4 w-4" />{error}</div><button onClick={() => void load()} className="btn-ghost px-3 py-1.5 text-[12px]">Try again</button></Panel>}
    <section className="hq-rise grid gap-5 xl:grid-cols-[minmax(0,3fr)_minmax(230px,1fr)]" style={rise(160)}><div><div className="mb-3 flex items-end justify-between gap-4"><div><div className="eyebrow">Operational ledger</div><h2 className="mt-1.5 text-[20px] font-semibold tracking-[-0.02em] text-[var(--text)]">Event Log</h2></div><div className="num text-right text-[11px] text-[var(--text-3)]">Showing {visible.length} of {filtered.length} matching</div></div><EventLog loading={loading} visible={visible} hasEvents={events.length > 0} clearFilters={clearFilters} /></div><aside className="space-y-5"><RankPanel title="By Type" rows={typeCounts} formatLabel={label} empty="No event types loaded." /><RankPanel title="Top Sources" rows={topSources} empty="No event titles loaded." limit={5} /></aside></section>
  </div>;
}

function ThroughputChart({ buckets }: { buckets: ThroughputBucket[] }) { if (!buckets.length) return <div className="mt-6 flex h-40 flex-col items-center justify-center rounded-[var(--r-md)] border border-dashed border-[var(--line-strong)] text-center"><TerminalSquare className="h-5 w-5 text-[var(--text-4)]" /><p className="mt-2 text-[12px] text-[var(--text-3)]">No valid event timestamps loaded.</p></div>; const max = Math.max(1, ...buckets.map((bucket) => bucket.count)); const points = buckets.map((bucket, index) => `${buckets.length === 1 ? 50 : index / (buckets.length - 1) * 100},${42 - bucket.count / max * 34}`).join(" "); const area = `0,42 ${points} 100,42`; return <div className="mt-5"><div className="h-40 rounded-[var(--r-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--surface-2)_55%,transparent)] p-3"><svg viewBox="0 0 100 46" preserveAspectRatio="none" className="h-full w-full" role="img" aria-label={`Event throughput across ${buckets.length} timestamp buckets`}><defs><linearGradient id="activity-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--accent)" stopOpacity="0.32" /><stop offset="100%" stopColor="var(--accent)" stopOpacity="0.02" /></linearGradient></defs><line x1="0" y1="42" x2="100" y2="42" stroke="var(--line-strong)" strokeWidth="0.4" /><polygon points={area} fill="url(#activity-area)" /><polyline points={points} fill="none" stroke="var(--accent)" strokeWidth="1.25" vectorEffect="non-scaling-stroke" strokeLinejoin="round" strokeLinecap="round" />{buckets.map((bucket, index) => <circle key={bucket.start} cx={buckets.length === 1 ? 50 : index / (buckets.length - 1) * 100} cy={42 - bucket.count / max * 34} r="0.8" fill="var(--accent)" vectorEffect="non-scaling-stroke"><title>{`${bucket.count} events · ${compactTime(bucket.start)}`}</title></circle>)}</svg></div><div className="mt-2 flex justify-between text-[10px] text-[var(--text-4)]"><span>{compactTime(buckets[0].start)}</span><span>Peak bucket: {max}</span><span>{compactTime(buckets[buckets.length - 1].start)}</span></div></div>; }
function Snapshot({ label: heading, value, note }: { label: string; value: string; note: string }) { return <div className="min-w-0"><div className="eyebrow !text-[9px]">{heading}</div><div className="num mt-2 text-[20px] font-semibold text-[var(--text)]">{value}</div><div className="mt-1 truncate text-[10.5px] text-[var(--text-3)]" title={note}>{note}</div></div>; }
function RankPanel({ title, rows, empty, limit, formatLabel = (value) => value }: { title: string; rows: CountRow[]; empty: string; limit?: number; formatLabel?: (value: string) => string }) { const shown = limit ? rows.slice(0, limit) : rows; const max = Math.max(1, ...shown.map((row) => row.count)); return <Panel className="p-4 sm:p-5"><div className="flex items-center justify-between"><h3 className="text-[14px] font-semibold text-[var(--text)]">{title}</h3><span className="num text-[10px] text-[var(--text-4)]">Loaded result</span></div>{shown.length ? <div className="mt-5 space-y-4">{shown.map((row, index) => <div key={row.label}><div className="mb-1.5 flex items-center justify-between gap-3"><span className="truncate text-[11.5px] text-[var(--text-2)]" title={formatLabel(row.label)}>{title === "Top Sources" && <span className="num mr-2 text-[var(--text-4)]">{index + 1}</span>}{formatLabel(row.label)}</span><span className="num shrink-0 text-[10.5px] text-[var(--text-3)]">{row.count}</span></div><div className="h-1 overflow-hidden rounded-full bg-[var(--surface-3)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{ width: `${row.count / max * 100}%`, opacity: title === "Top Sources" ? 0.65 : 0.9 }} /></div></div>)}</div> : <p className="mt-5 text-[11.5px] text-[var(--text-3)]">{empty}</p>}</Panel>; }
function EventLog({ loading, visible, hasEvents, clearFilters }: { loading: boolean; visible: AgentEvent[]; hasEvents: boolean; clearFilters: () => void }) { if (loading) return <Panel className="space-y-2 p-3">{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} className="h-16" />)}</Panel>; if (!visible.length) return <Panel className="flex min-h-64 flex-col items-center justify-center p-6 text-center"><TerminalSquare className="h-6 w-6 text-[var(--text-3)]" /><p className="mt-3 text-[13px] font-medium text-[var(--text-2)]">{hasEvents ? "No events match these filters" : "No activity recorded"}</p><p className="mt-1 max-w-sm text-[12px] text-[var(--text-3)]">{hasEvents ? "Adjust the type, level, or search query to widen the current result." : "Real AgentEvent records will appear here when Hermes or the Bridge records activity."}</p>{hasEvents && <button onClick={clearFilters} className="btn-ghost mt-4 px-3 py-1.5 text-[12px]">Clear filters</button>}</Panel>; return <Panel className="overflow-hidden"><div className="divide-y divide-[var(--line)]">{visible.map((event) => <article key={event.id} className="grid gap-3 px-4 py-4 transition-colors hover:bg-[var(--surface-2)] md:grid-cols-[145px_100px_minmax(220px,1fr)_80px] md:items-start md:gap-4"><time className="num text-[10.5px] leading-relaxed text-[var(--text-3)]" dateTime={event.createdAt}>{formatTime(event.createdAt)}</time><div><div className="truncate text-[12px] font-medium text-[var(--text-2)]">{event.agent || "Unattributed"}</div><div className="mt-1 text-[10.5px] text-[var(--text-4)]">{label(event.kind)}</div></div><div className="min-w-0"><h3 className="text-[13px] font-medium leading-snug text-[var(--text)]">{event.title}</h3>{event.detail && <p className="mt-1.5 whitespace-pre-wrap text-[12px] leading-relaxed text-[var(--text-3)]">{event.detail}</p>}</div><div className="md:text-right"><Pill tone={tone(event.level)} className="!px-2 !py-0.5 !text-[10px]">{label(event.level)}</Pill></div></article>)}</div></Panel>; }
