"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Clock3, Filter, RefreshCw, Search, TerminalSquare, UsersRound } from "lucide-react";
import { Panel, Pill, Skeleton, rise } from "@/components/ui/kit";

type AgentEvent = { id: string; kind: string; title: string; detail: string | null; agent: string; level: string; meta?: unknown; createdAt: string };
type KindFilter = "all" | "run" | "status";
function parseDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; }
function formatTime(value: string) { const date = parseDate(value); return date ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit", second: "2-digit" }).format(date) : "Unknown time"; }
function timeAgo(value: string | null) { if (!value) return "—"; const date = parseDate(value); if (!date) return "—"; const seconds = Math.round((date.getTime() - Date.now()) / 1000); const f = new Intl.RelativeTimeFormat(undefined, { numeric: "auto" }); if (Math.abs(seconds) < 60) return f.format(seconds, "second"); const minutes = Math.round(seconds / 60); if (Math.abs(minutes) < 60) return f.format(minutes, "minute"); const hours = Math.round(minutes / 60); return Math.abs(hours) < 48 ? f.format(hours, "hour") : f.format(Math.round(hours / 24), "day"); }
function label(value: string) { return value.replace(/[_-]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function tone(level: string): "neutral" | "up" | "down" | "warn" | "accent" { const value = level.toLowerCase(); if (["error", "down", "fail", "critical"].some((part) => value.includes(part))) return "down"; if (["warn", "attention"].some((part) => value.includes(part))) return "warn"; if (["up", "success", "online"].some((part) => value.includes(part))) return "up"; if (["active", "run"].some((part) => value.includes(part))) return "accent"; return "neutral"; }

export default function ActivityPage() {
  const [events, setEvents] = useState<AgentEvent[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const [kind, setKind] = useState<KindFilter>("all"); const [level, setLevel] = useState("all"); const [query, setQuery] = useState("");
  const load = useCallback(async (quiet = false) => { if (quiet) setRefreshing(true); else setLoading(true); setError(null); try { const response = await fetch("/api/hermes/activity?take=100", { cache: "no-store" }); if (!response.ok) throw new Error(`Request failed (${response.status})`); const data = await response.json() as { events?: AgentEvent[] }; setEvents(data.events ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load activity."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { const frame = requestAnimationFrame(() => { void load(); }); return () => cancelAnimationFrame(frame); }, [load]);
  const identities = useMemo(() => [...new Set(events.map((event) => event.agent?.trim()).filter(Boolean))].sort(), [events]);
  const kinds = useMemo(() => [...new Set(events.map((event) => event.kind?.trim()).filter(Boolean))].sort(), [events]);
  const levels = useMemo(() => [...new Set(events.map((event) => event.level?.trim()).filter(Boolean))].sort(), [events]);
  const visible = useMemo(() => { const needle = query.trim().toLowerCase(); return events.filter((event) => { if (kind !== "all" && event.kind.toLowerCase() !== kind) return false; if (level !== "all" && event.level !== level) return false; return !needle || [event.agent, event.title, event.detail, event.kind, event.level].some((value) => value?.toLowerCase().includes(needle)); }); }, [events, kind, level, query]);
  const clearFilters = () => { setKind("all"); setLevel("all"); setQuery(""); };

  return <div className="relative z-10 w-full space-y-7 pb-16 pt-1">
    <header className="hq-rise flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between" style={rise(0)}><div><div className="eyebrow mb-1.5">Hermes operations</div><h1 className="text-[30px] font-semibold tracking-[-0.03em] text-[var(--text)] sm:text-[34px]">Activity</h1><p className="mt-1 max-w-xl text-[12.5px] text-[var(--text-3)]">Live and historical events across Hermes operations.</p></div><button onClick={() => void load(true)} disabled={refreshing} className="btn-ghost flex items-center gap-2 self-start px-3.5 py-2 text-[12px] sm:self-auto"><RefreshCw className={`h-3.5 w-3.5 ${refreshing ? "animate-spin" : ""}`} />Refresh</button></header>
    <section className="hq-rise grid grid-cols-2 gap-3 lg:grid-cols-4" style={rise(60)}><Summary icon={<Activity />} label="Events loaded" value={loading ? "…" : String(events.length)} note="Current API result" /><Summary icon={<Clock3 />} label="Latest event" value={loading ? "…" : timeAgo(events[0]?.createdAt ?? null)} note="Within loaded result" /><Summary icon={<UsersRound />} label="Attributed identities" value={loading ? "…" : String(identities.length)} note={identities.join(", ") || "None loaded"} /><Summary icon={<Filter />} label="Event types" value={loading ? "…" : String(kinds.length)} note={kinds.map(label).join(", ") || "None loaded"} /></section>
    <section className="hq-rise" style={rise(110)}><Panel className="p-3 sm:p-4"><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap gap-1.5">{(["all", "run", "status"] as KindFilter[]).map((item) => <button key={item} onClick={() => setKind(item)} className={`rounded-lg px-3 py-1.5 text-[11.5px] font-medium transition-colors ${kind === item ? "bg-[var(--surface-3)] text-[var(--text)]" : "text-[var(--text-3)] hover:bg-[var(--surface-2)] hover:text-[var(--text-2)]"}`}>{label(item)}<span className="num ml-1.5 text-[var(--text-4)]">{item === "all" ? events.length : events.filter((event) => event.kind.toLowerCase() === item).length}</span></button>)}</div><div className="flex flex-col gap-2 sm:flex-row"><select aria-label="Filter by event level" value={level} onChange={(event) => setLevel(event.target.value)} className="rounded-lg border border-[var(--line)] bg-[var(--surface-2)] px-3 py-2 text-[12px] text-[var(--text-2)] outline-none"><option value="all">All levels</option>{levels.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><label className="relative min-w-0 sm:w-64"><Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[var(--text-4)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search event history" className="w-full rounded-lg border border-[var(--line)] bg-[var(--surface-2)] py-2 pl-9 pr-3 text-[12px] text-[var(--text)] outline-none placeholder:text-[var(--text-4)]" /></label></div></div></Panel></section>
    {error && <Panel className="flex flex-col items-start justify-between gap-3 p-4 sm:flex-row sm:items-center"><div className="flex items-center gap-2 text-[13px] text-[var(--down)]"><AlertTriangle className="h-4 w-4" />{error}</div><button onClick={() => void load()} className="btn-ghost px-3 py-1.5 text-[12px]">Try again</button></Panel>}
    <section className="hq-rise" style={rise(160)}><div className="mb-3 flex items-end justify-between"><div><div className="eyebrow">Operational ledger</div><h2 className="mt-1.5 text-[20px] font-semibold tracking-[-0.02em] text-[var(--text)]">Event history</h2></div><div className="num text-[11px] text-[var(--text-3)]">{visible.length} of {events.length} loaded events</div></div>
      {loading ? <Panel className="space-y-2 p-3">{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} className="h-16" />)}</Panel> : visible.length ? <Panel className="overflow-hidden"><div className="divide-y divide-[var(--line)]">{visible.map((event) => <article key={event.id} className="grid gap-3 px-4 py-4 transition-colors hover:bg-[var(--surface-2)] md:grid-cols-[155px_110px_minmax(240px,1fr)_90px] md:items-start md:gap-5"><time className="num text-[10.5px] leading-relaxed text-[var(--text-3)]" dateTime={event.createdAt}>{formatTime(event.createdAt)}</time><div><div className="text-[12px] font-medium text-[var(--text-2)]">{event.agent || "Unattributed"}</div><div className="mt-1 text-[10.5px] text-[var(--text-4)]">{label(event.kind)}</div></div><div className="min-w-0"><h3 className="text-[13px] font-medium leading-snug text-[var(--text)]">{event.title}</h3>{event.detail && <p className="mt-1.5 whitespace-pre-wrap text-[12px] leading-relaxed text-[var(--text-3)]">{event.detail}</p>}</div><div className="md:text-right"><Pill tone={tone(event.level)} className="!px-2 !py-0.5 !text-[10px]">{label(event.level)}</Pill></div></article>)}</div></Panel> : <Panel className="flex min-h-64 flex-col items-center justify-center p-6 text-center"><TerminalSquare className="h-6 w-6 text-[var(--text-3)]" /><p className="mt-3 text-[13px] font-medium text-[var(--text-2)]">{events.length ? "No events match these filters" : "No activity recorded"}</p><p className="mt-1 max-w-sm text-[12px] text-[var(--text-3)]">{events.length ? "Adjust the type, level, or search query to widen the current result." : "Real AgentEvent records will appear here when Hermes or the Bridge records activity."}</p>{events.length > 0 && <button onClick={clearFilters} className="btn-ghost mt-4 px-3 py-1.5 text-[12px]">Clear filters</button>}</Panel>}
    </section>
  </div>;
}
function Summary({ icon, label: heading, value, note }: { icon: React.ReactElement<{ className?: string }>; label: string; value: string; note: string }) { return <Panel className="min-h-[128px] p-4 sm:p-5"><div className="flex items-center justify-between"><div className="eyebrow !text-[9.5px]">{heading}</div><span className="text-[var(--text-4)]">{icon}</span></div><div className="num mt-4 text-[21px] font-semibold text-[var(--text)]">{value}</div><div className="mt-1 truncate text-[10.5px] text-[var(--text-3)]" title={note}>{note}</div></Panel>; }
